language: java

jdk:
#  - oraclejdk8
  - openjdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P noarrow

script: mvn test -B -P noarrow

after_success:
  - bash <(curl -s https://codecov.io/bash)
